### ISSUE TITLE
Compilation error on macOS 11.6

### ISSUE THREAD

**Issue by maxibor** [miwipe/ngsLCA#21]
Hi @miwipe , 
While working ont the review of ngsLCA, I tried to compile it following the README's instruction (as of [f118505](https://github.com/miwipe/ngsLCA/commit/f118505bc80f6dceccf023dafbc0081c85c4bbce)), however, I encountered some errors (see log attached).
Compilation worked fine on Ubuntu 20.04

[ngsLCA_build_log.txt](https://github.com/miwipe/ngsLCA/files/8363190/ngsLCA_build_log.txt)
